version: '3'

services:
  postgres:
    image: 'postgres:10-alpine'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:4.0.10-alpine'
    command: redis-server --requirepass unbabel
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'
  
  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "project.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/project'
    ports:
      - '8000:8000'
  
  celery:
    build: .
    command: celery worker -l info -A project.blueprints.page.tasks -B
    env_file:
      - '.env'
    volumes:
      - '.:/project'

volumes:
  postgres:
  redis:
